### ISSUE TITLE
Split gulp tasks by files

### ISSUE THREAD

**Issue by AbraaoAlves** [devevents/conf-app-boilerplate#10]

**Comment by AbraaoAlves** [comment]
We can use [gulp-angular generator](https://github.com/Swiip/generator-gulp-angular) to fast fix this issue and others related with gulp tasks. ex: minify, sourcempas, watch files, build dev/prod, ...

**Comment by ythecombinator** [comment]
Hey @AbraaoAlves ! These days've been so crazy, so I couldn't give this project the deserved attention, sorry for my delay. But now it's time to make things happen and I'd like to start by this issue :smile: 

I haven't looked in detail the project you mentioned yet... and, in fact, I had never done task spliting in any project - so I'm kinda newbie; but these days, in another personal project, I ended up using this [approach](https://github.com/mabrasil/lumberpack/blob/master/gulpfile.js) ... What do you think? Could it be suitable for our case?

**Comment by ythecombinator** [comment]
Hey @AbraaoAlves , I ended up by putting all the Gulp tasks in the [`tasks/`](https://github.com/devevents/conf-app-boilerplate/tree/master/gulp/tasks) folder. Each one is now a module with a function which is required into tasks defined in a `gulp` [module](https://github.com/devevents/conf-app-boilerplate/tree/master/gulp). I do think that this one can a good approach, so, for now, I'll close this issue.

**Comment by AbraaoAlves** [comment]
Grate job @mabrasil :+1: 

Recently a find this [post](http://macr.ae/article/splitting-gulpfile-multiple-files.html), and i review my concept by about this.

What do you thing about second approach?
