### ISSUE TITLE
Use Jade as a template engine

### ISSUE THREAD

**Issue by ythecombinator** [devevents/conf-app-boilerplate#4]
The use of [Jade Engine](http://jade-lang.com/) is intended to make the app templates' code more beautiful and **easier to maintain**. It also aims to solve some problems such as missing or mal-matched closing tags.

All `.jade` files organization would follow the current structure (**divided by functionality**): 

```
root
│   README.md
│   LICENSE.md 
│   ...
└───app
    ├───about
    │   │   about.jade
    │   │   ...
    │
    └───location
    │   │   location.jade
    │   │   ...
    └───...
└───www
    ├───app
        ├───about
        │   │   about.html
        │   │   ...
        │
       └───location
        │   │   location.html
        │   │   ...
        └───...
```

**How-to**: This can be done by adding a Gulp plugin that [compiles jade to html](https://www.npmjs.com/package/gulp-jade) + a Gulp task to do so; and then rewriting the templates in jade.

**Comment by felipesousa** [comment]
:+1:

**Comment by ythecombinator** [comment]
Jade applied and templates successfully updated from commits 76cebb5d1c310b499fd886ceb21d3fdc61a88e13 to 37c6e487082c43bd1be29ac69a04a67e432be57a.
